export const enum Creneau {
  MECREDI_MATIN = 'MECREDI_MATIN',
  MERCREDI_APRES_MIDI = 'MERCREDI_APRES_MIDI',
  SAMEDI_MATIN = 'SAMEDI_MATIN',
  SAMEDI_APRES_MIDI = 'SAMEDI_APRES_MIDI',
  DIMANCHE_MATIN = 'DIMANCHE_MATIN',
  DIMANCHE_APRES_MIDI = 'DIMANCHE_APRES_MIDI'
}
